# DAX Measures — Finance Report Dashboard
This document lists all DAX measures used in the Power BI report, along with a short explanation of what each one calculates.

## 1. Core Financial Metrics

## Total Revenue
Calculates total income generated by the company from its operations.

TotalRevenue = CALCULATE(SUM(revenue_expense[Amount]), revenue_expense[Revenue or expense] = "Revenue")

## Total Expense
Sum of all expenses (COGS, Opex, Interest and Tax) incurred by the business

TotalExpense = CALCULATE(SUM(revenue_expense[Amount]), revenue_expense[Revenue or expense] = "Expense")

## COGS (Cost of Goods)
Direct costs attributable to the production of goods sold.

COGS = CALCULATE(SUM(revenue_expense[Amount]), revenue_expense[Revenue / Expense Group] = "COGS")

## Opex
Total operating expenses incurred during regular business operations.

Opex = Opex = CALCULATE(SUM(revenue_expense[Amount]), revenue_expense[Revenue / Expense Group] = "Opex")

## Interest and Tax
Costs associated with interest and taxes, important for understanding overall profitability.

Int and Tax = CALCULATE(SUM(revenue_expense[Amount]), revenue_expense[Revenue / Expense Group] = "Interest and Tax"

## Gross Profit
Profit the company makes after deducting the costs associated with making and selling its products.

Gross Profit = [TotalRevenue] - [COGS]

## Gross Profit Margin 
Percentage of revenue that exceeds COGS, reflecting efficiency in production and pricing.

Gross Profit Margin = DIVIDE([Gross Profit], [TotalRevenue], 0)

## EBIT
Profitability from operations, excluding the costs of interest and tax.

EBIT = [Gross Profit] - [Opex]

## EBIT Margin 
Operating profitability as a percentage of total revenue.

EBIT Margin = DIVIDE([EBIT], [TotalRevenue], 0)

## Net Profit 
Actual profit after all expenses — COGS, Opex, interest, and taxes — have been deducted.

Net Profit = [TotalRevenue] - [TotalExpense]

## Net Profit Margin 
How much of each dollar earned translates into profit.

Net Profit Margin = DIVIDE([Net Profit], [TotalRevenue], 0)

## 2. Month-over-Month (MoM) Growth Measures

## PrevMonthRev (Previous Month Revenue)
Reference measures that pull revenue value from the previous month, used to calculate MoMRev growth.  

PrevMonthRev = CALCULATE( [TotalRevenue], DATEADD(Finance[Date], -1, MONTH)) + 0

## PrevMonthExp (Previous Month Expenses)
Reference measures that pull expenses value from the previous month, used to calculate MoMExp growth.

PrevMonthExp = CALCULATE([TotalExpense], DATEADD(Finance[Date], -1, MONTH))

## PrevMonthGP (Previous Month Gross Profit)
Reference measures that pull Gross Profit value from the previous month, used to calculate MoMGP growth.

PrevMonthGP = CALCULATE([Gross Profit], DATEADD(Finance[Date], -1, MONTH))

## PrevMonthNP (Previous Month Net Profit)
Reference measures that pull Net Profit value from the previous month, used to calculate MoMNP growth .

PrevMonthNP = CALCULATE([Net Profit], DATEADD(Finance[Date], -1, MONTH))

## MoMRev (Month over Month Revenue)
Change in revenue compared to the previous month.

MoMRev = [TotalRevenue] - [PrevMonthRev]

## MoMRev%
Month-over-month growth rate in revenue.

MoMRev% = DIVIDE([MoMRev], [PrevMonthRev], 0)

## MoMExp (Month over Month Expense)
Change in expenses compared to the previous month.

MoMExp = [TotalExpense] - [PrevMonthExp]

## MoMExp%
Month-over-month growth rate in expenses.

MoMExp% = DIVIDE([MoMExp], [PrevMonthExp], 0)

## MoMGP (Month over Month Gross Profit)
Change in gross profit compared to the previous month.

MoMGP = [Gross Profit] - [PrevMonthGP]

## MoMGP%
Month-over-month growth rate in gross profit.

MoMGP% = DIVIDE([MoMGP], [PrevMonthGP], 0)

## MoMNP (Month over Month Net Profit)
Change in net profit compared to the previous month.

MoMNP = [Net Profit] - [PrevMonthNP]

## MoMNP%
Month-over-month growth rate in net profit.

MoMNP% = DIVIDE([MoMNP], [PrevMonthNP], 0)

## 3. Target / Budget Comparison Measures

## Target Revenue
The budgeted/target revenue figure used to compare against actual performance.

TargetRevenue = 6000000


## TargetExpense
The budgeted/target expense figure used to compare against actual performance.

TargetExpense = 4000000

## Target Month Revenue
Target revenue for the selected month, used to plot the monthly actual-vs-target comparison line.

Target Month Revenue = 18000000/12

## 4. Conditional Formatting (Dynamic Color) Measures
These measures return color values used to dynamically format KPI cards.

## Revbgcolor / RevValueColor
Background and text color for the Revenue card.

Revbgcolor = IF([MoMRev]>0, "#CFF5DA", "#F5CFCF")

RevValueColor = IF([MoMRev]>0, "Green", "Red")

## Expbgcolor / ExpValueColor
Background and text color for the Expense card.

Expbgcolor = IF([MoMExp]>0, "#F5CFCF", "#CFF5DA")

ExpValueColor = IF([MoMExp]>0, "Red","Green")

## GPbgcolor / GPValueColor
Background and text color for the Gross Profit card.

GPbgcolor = IF([MoMGP]>0, "#CFF5DA", "#F5CFCF")

GPValueColor = IF([MoMG]>0, "Green", "Red")

## NPbgcolor / NPValueColour
Background and text color for the Net Profit card.

NPbgcolor = IF([MoMNP]>0, "#CFF5DA", "#F5CFCF")

NPValueColour = IF([MoMNP]>0, "Green","Red")
